# Generated by Django 4.2.7 on 2024-07-09 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_protein', models.FloatField(default=0)),
                ('total_carbohydrates', models.FloatField(default=0)),
                ('total_fat', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'breakfast'), ('second_breakfast', 'second_breakfast'), ('lunch', 'lunch'), ('afternoon_snack', 'afternoon_snack'), ('dinner', 'dinner')], max_length=20)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LifeTrackAPI.day')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('protein_per_100g', models.FloatField()),
                ('carbohydrates_per_100g', models.FloatField()),
                ('fat_per_100g', models.FloatField()),
                ('calories_per_100g', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MealProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gramature', models.FloatField(default=100)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LifeTrackAPI.meal')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LifeTrackAPI.product')),
            ],
            options={
                'unique_together': {('meal', 'product')},
            },
        ),
        migrations.AddField(
            model_name='meal',
            name='products',
            field=models.ManyToManyField(related_name='meals', through='LifeTrackAPI.MealProduct', to='LifeTrackAPI.product'),
        ),
    ]
