# Generated by Django 4.2.7 on 2024-06-14 15:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LifeTrackAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='calories_per_100g',
            field=models.FloatField(default=50),
        ),
        migrations.AlterUniqueTogether(
            name='day',
            unique_together={('user', 'date')},
        ),
    ]
