# Generated by Django 4.2.7 on 2024-07-10 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LifeTrackAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(max_length=5)),
                ('chest_circ', models.FloatField(max_length=5)),
                ('waist_circ', models.FloatField(max_length=5)),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
