# Generated by Django 4.2.7 on 2024-06-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LifeTrackAPI', '0002_product_calories_per_100g_alter_day_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='calories_per_100g',
            field=models.FloatField(),
        ),
    ]
