# Generated by Django 4.2.7 on 2024-06-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LifeTrackAPI', '0002_remove_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='products',
            field=models.ManyToManyField(related_name='product', to='LifeTrackAPI.product'),
        ),
    ]
